version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
      - postgres

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    links:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: HackTheRoot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  pg_data: